export const keyMapper = (key: string): string | null => {
    switch (key) {
        case 'Enter':
            return 'Enter';
        case 'Backspace':
        case 'Delete':
            return 'Delete';
        case '\'':
        case 'w':
        case 'W':
            return '\'';
        case 'א':
        case 'T':
        case 't':
            return 'א';
        case 'ב':
        case 'C':
        case 'c':
            return 'ב';
        case 'ג':
        case 'D':
        case 'd':
            return 'ג';
        case 'ד':
        case 'S':
        case 's':
            return 'ד';
        case 'ה':
        case 'V':
        case 'v':
            return 'ה';
        case 'ו':
        case 'u':
        case 'U':
            return 'ו';
        case 'ז':
        case 'Z':
        case 'z':
            return 'ז';
        case 'ח':
        case 'J':
        case 'j':
            return 'ח';
        case 'ט':
        case 'Y':
        case 'y':
            return 'ט';
        case 'י':
        case 'h':
        case 'H':
            return 'י';
        case 'כ':
        case 'F':
        case 'f':
        case 'ך':
        case 'L':
        case 'l':
            return 'כ';
        case 'ל':
        case 'k':
        case 'K':
            return 'ל';
        case 'מ':
        case 'N':
        case 'n':
        case 'ם':
        case 'O':
        case 'o':
            return 'מ';
        case 'נ':
        case 'b':
        case 'B':
        case 'ן':
        case 'I':
        case 'i':
            return 'נ';
        case 'ס':
        case 'X':
        case 'x':
            return 'ס';
        case 'ע':
        case 'G':
        case 'g':
            return 'ע';
        case 'פ':
        case 'p':
        case 'P':
        case 'ף':
        case ';':
            return 'פ';
        case 'צ':
        case 'M':
        case 'm':
        case 'ץ':
        case '.':
            return 'צ';
        case 'ק':
        case 'E':
        case 'e':
            return 'ק';
        case 'ר':
        case 'r':
        case 'R':
            return 'ר';
        case 'ש':
        case 'a':
        case 'A':
            return 'ש';
        case 'ת':
        case ',':
            return 'ת';
        default:
            return null;
    }
};
